name: Release
on:
  push:
    branches-ignore:
      - '*'
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      matrix:
        component:
          - identity
          - region
          - kubernetes
          - compute
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: generate
        uses: openapi-generators/openapitools-generator-action@v1
        with:
          generator: html
          openapi-url: "https://raw.githubusercontent.com/unikorn-cloud/${{ matrix.component }}/blob/${{ github.ref_name }}/pkg/openapi/server.spec.yaml"
          command-args: -o artifact
      - name: upload-artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.component }}
          path: artifact
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    needs:
      - build
    steps:
      - name: make-root
        run: mkdir -p root
      - name: download-identity-artifact
        uses: actions/download-artifact@v4
        with:
          pattern: identity
          path: root
      - name: download-region-artifact
        uses: actions/download-artifact@v4
        with:
          pattern: region
          path: root
      - name: download-kubernetes-artifact
        uses: actions/download-artifact@v4
        with:
          pattern: kubernetes
          path: root
      - name: download-compute-artifact
        uses: actions/download-artifact@v4
        with:
          pattern: compute
          path: root
      - name: upload-artifact
        uses: actions/upload-pages-artifact@v3
        with:
          name: github-pages
          path: root
      - name: deploy
        uses: actions/deploy-pages@v4
