name: Release
on:
  push:
    branches-ignore:
      - '*'
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      matrix:
        component:
          - identity
          - region
          - kubernetes
          - compute
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: generate
        uses: openapi-generators/openapitools-generator-action@v1
        with:
          generator: html
          openapi-url: "https://raw.githubusercontent.com/unikorn-cloud/${{ matrix.component }}/refs/heads/main/pkg/openapi/server.spec.yaml"
          command-args: -o ${{ matrix.component }}
      - name: upload-artifact
        uses: actions/upload-artifact@v4
        with:
          name: docs-component-${{ matrix.component }}
          path: ${{ matrix.component }}
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    needs:
      - build
    steps:
      - name: make-root
        run: mkdir root
      - name: download-artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: docs-component-*
          merge-multiple: true
          path: root
      - name: upload-artifact
        uses: actions/upload-artifact@v4
        with:
          name: docs-archive
          path: root
      - name: deploy
        uses: actions/deploy-pages@v4
        with:
          artifact-name: docs-archive
